//
// Created by josh on 7/8/22.
//

#ifndef OXDNA_CUDAALLOSTERICPATCHYINTERACTION_H
#define OXDNA_CUDAALLOSTERICPATCHYINTERACTION_H


class CUDAAllostericPatchyInteraction {

};


#endif //OXDNA_CUDAALLOSTERICPATCHYINTERACTION_H
